services:
  db:
    image: mariadb:10.11
    container_name: good-scan-db
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: good
      MARIADB_USER: cccmdev
      MARIADB_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - good-scan-db-data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  good-scan-db-data:
